### ISSUE TITLE
Add "Run Applescript" action

### ISSUE THREAD

**Issue by rxhanson** [rxhanson/Multitouch-Bugs#12]
Adding the ability to run applescripts as a gesture action would also require some updates to the UI to allow file selection.

**Comment by lorenzofanchi** [comment]
This would be awesome to have! My Finder windows are acting wonky sometimes (classic size/position problems) and I have a simple apple script to resize and reposition the window. Would be great to be able to trigger with a multitouch trigger!

**Comment by rxhanson** [comment]
Sounds good, I'll bump this up in priority. 

On a side note, I've actually been considering rolling in some more window management actions so that an external window management app might not be necessary for some users.

**Comment by rxhanson** [comment]
As of v1.16, there's the ability to execute a bash command (selectable from Execute -> Bash Command in the action selector). From bash, osascript can be executed, and therefore this issue is now covered, albeit slightly indirectly. I'm going to close this one out, and if running via bash isn't sufficient for any reason, this one can be reopened.
