### ISSUE TITLE
Add "finger roll" gesture

### ISSUE THREAD

**Issue by ab1470** [rxhanson/Multitouch-Bugs#25]
Jitouch 2 has an "Index to pinky" gesture that I like a lot: you basically roll your fingers on the trackpad, starting from index and ending with pinky. It's really nice for entering/exiting fullscreen mode on apps!

**Comment by ab1470** [comment]
ps: thanks for making this app, it's great! I'd love to fully migrate from Jitouch2, but it has a few gestures that Multitouch doesn't yet have, and I'd really miss them if I were to leave Jitouch behind!

**Comment by rxhanson** [comment]
Unfortunately, I don't have plans to implement the finger roll gesture, and I'm closing out issues to clean things up a bit. I don't mind coming back to it if there's high demand, but it's one that I haven't had anyone else looking for. Thanks though!
