### ISSUE TITLE
App-specific gestures

### ISSUE THREAD

**Issue by lorenzofanchi** [rxhanson/Multitouch-Bugs#26]
Great work on the app so far! 
It would be very nice if we could set gestures for specific apps, next to global gestures. The App-specific ones would override the global ones when the app in question has focus

**Comment by rxhanson** [comment]
Thanks!
If you don't mind me asking, what is your specific use case? Which apps would you be looking to set specific gestures for? 
Keeping the gestures global was an intentional decision to keep Multitouch as simple to configure as possible. A configuration model like BTT doesn't quite fit with the design of Multitouch, but there are some ways I've thought about to elegantly provide per app configuration.

**Comment by lorenzofanchi** [comment]
I have a couple set up in Jitouch on my work computer, can't remember exactly which. Will update the post tomorrow after checking my settings!

**Comment by lorenzofanchi** [comment]
I actually don't have a specific use-case scenario at the moment. On my work computer I'd set up different keyboard shortcuts for Finder and Chrome to switch tabs, as they require different key combo's, but you've got that covered in Multitouch :)

Still, I think it could be a cool feature :)

**Comment by rxhanson** [comment]
Thanks for getting back to me on this one. I’ve been considering reworking some of the “action selection” UI for quite some time now, and will keep this in mind when I get into it.

**Comment by lorenzofanchi** [comment]
I have a case!

The Papers app uses Shift + Cmd + Left/Right to move through tabs and doesn't work 'out-of-the-box' with MultiTouch. Would be nice to be able to set this as a custom gesture for this app only.

**Comment by rxhanson** [comment]
I'll go ahead and add the Papers app in to the "Apps with tabs" category for the next release. I'll still look into making a general solution for this in the future, though.

**Comment by rxhanson** [comment]
My how the time flies. I've got my first cut at this in v1.18, currently in pre-release. It can be downloaded at https://multitouch.app/versions
