### ISSUE TITLE
Palm rejection on rest two / tap one

### ISSUE THREAD

**Issue by ab1470** [rxhanson/Multitouch-Bugs#34]
The palm of my left hand often rests on the edge of huge trackpad on the newest generation MacBook Pro. With my palm in this position, Multitouch will sometimes pick it up as a third finger when I use my right hand to scroll with two fingers.

**Comment by rxhanson** [comment]
Similar to https://github.com/Brass-Monkery/Multitouch-Bugs/issues/30, I added in some filtering for touches that appear to be a palm. Palm rejection can be pretty complicated, but hopefully this fix will work for you. There are additional complexities that I can add to Multitouch to work on this problem, but let's see how this one works for you first, if you don't mind.

Just like https://github.com/Brass-Monkery/Multitouch-Bugs/issues/30, I've added in defaults configuration to tweak this as needed:

`defaults write com.brassmonkery.Multitouch filterLargeTouches -float 8`

You'll have to restart Multitouch after executing this in Terminal.

8 is the default I use in Multitouch, and I recommend going up or down in increments of 1. A higher value means only larger touches will be rejected.

Let me know how this works out for you, and we can take it from there. Thanks.

**Comment by ab1470** [comment]
It seems to me that the palm rejection is just a matter of distance. I can have my left palm on the far left edge of the trackpad (where it usually is, with my fingers resting on the keyboard) and two fingers of my right hand on the far right edge of the trackpad, and it will trigger rest two / tap one. Can you just require the the three fingers be less than a certain distance apart in order to trigger that gesture?

**Comment by rxhanson** [comment]
Ideally, I'd like to solve palm rejection in a general way. As a shorter term fix it's probably just as well to require a closer proximity on the three fingers. If I can get the palm rejection tuned in a reasonable amount of time, I'll give that a go.

**Comment by rxhanson** [comment]
Sorry for not reporting back on this issue, but Multitouch did get updated palm rejection logic in versions that came after last December. Closing this one out, just to clean out issues, but if it's still a problem feel free to reopen it.
