### ISSUE TITLE
UI issues when selecting actions

### ISSUE THREAD

**Issue by lorenzofanchi** [rxhanson/Multitouch-Bugs#37]
Hi, the category/action selection UI behaves inconsistently when selecting a category/action from the dropdown list. First of all, when selecting an action _category_, the actions dropdown is immediately triggered (this might be intentional). You can also notice some visual glitches on the main window. Secondly, when selecting an action, the wrong action is set (see result in main window) and you have to go back to configure the right one. See video for more clarification.

https://streamable.com/kpnty

Thanks and best

**Debug info**
Multitouch: 1.9 (41)
macOS: Version 10.14.4 (Build 18E226)
Model: MacBookPro14,3
Devices: ["internalTrackpad2:144115188092633088:16777216"]
Multitouch Configuration: {"oneClickTopRight":{"type":4,"action":505},"threeTap":{"type":3,"action":300},"onePlusLeft":{"type":5,"action":501},"onePlusRight":{"type":5,"action":500}}
Avoid Private Framework: false

**Comment by rxhanson** [comment]
Thanks for the issue report! I'll push out a new release soon.

**Comment by rxhanson** [comment]
Alright, version 1.10 should have this fixed. Let me know if it still is buggy (or if you don't like this behavior).

Version 1.10 can be updated from within the app or downloaded at [https://multitouch.app/versions](https://multitouch.app/versions)

**Comment by lorenzofanchi** [comment]
Other than the main window visual glitches, everything seems fixed, thanks!

**Comment by lorenzofanchi** [comment]
The first action is still automatically selected after picking the category. Doesn't feel right to me.. I can't explain why, but it feels clunky/buggy. At least not something I'd expect to happen. I would venture a guess it doesn't align with the Apple HIG bible ;P

**Comment by rxhanson** [comment]
Ok, in v1.15 I've finally gotten a chance to change the UI to how I've wanted it to be for some time. With only one dropdown, this is no longer an issue. I'm going to close this one out. If you come across any issues with the new UI, feel free to open up a new issue. 

As a side note, I've broken a lot of Apple's HIG in Multitouch, haha. It's actually a nice freedom gained by not being able to put the app on the Mac App Store.
