### ISSUE TITLE
Settings of gestures are not saved after rebooting

### ISSUE THREAD

**Issue by ammnt** [rxhanson/Multitouch-Bugs#46]
Hello, I bought the license today and found out that settings of the added gestures are reset at rebooting of my macbook or just restarting the application. My configuration:
**Multitouch: 1.15 (62)
macOS: Version 10.14.5 (Build 18F132)
Model: MacBookPro14,1
Devices: ["internalTrackpad2:144115188092633088:16777216","magicMouse:288230377408548859:1256837115"]
Multitouch Configuration: {}
Avoid Private Framework: false**

Please, try to correct it. Thank you!

**Comment by rxhanson** [comment]
I’ve noticed this issue as well. I’ll take a look at it and push out a fix soon.

**Comment by rxhanson** [comment]
This should now be fixed in [v1.15.1](https://multitouch.app/versions). Thanks for reporting it. Please let me know if this version fixes the issue for you.

**Comment by ammnt** [comment]
Looks fine for now! Thank you so much for this fast response!
