### ISSUE TITLE
Add three finger swipe gesture on the magic mouse

### ISSUE THREAD

**Issue by rxhanson** [rxhanson/Multitouch-Bugs#50]

**Comment by alaaalii** [comment]
Yes! This is the only customization I need. I want to do the following on the magic mouse:

Three finger swipe up: Mission Control
Three finger swipe down: Application Windows

This makes it easy to view all of your open windows with a single easy action and complements all the other default swipe gestures. I've gotten so used to this when I was using another app.

Do you have an estimate on when this would be added?

**Comment by rxhanson** [comment]
I don't have an estimate, but I'll bump this up in priority - it'll be the next gesture that I add, since I've been meaning to add it in for a long time.

**Comment by rxhanson** [comment]
So I implemented this, but instantly didn't like it at all. Perfecting this gesture would take a really long time to get right, and would require doing some steps that I would prefer not to take from the perspective of how Multitouch handles gesture data. At the end of the day, it's just not something I have a desire to support. Apologies for any inconvenience this may have caused.
