### ISSUE TITLE
Three-finger click gestures not matched on 2019 MacBook Pro running Catalina

### ISSUE THREAD

**Issue by emilyst** [rxhanson/Multitouch-Bugs#55]
Hi, first of all, I'd like to say I strenuously enjoy the design of this program and the attention you've put into it! That's why I find this such a galling problem. I want to use it!

I'm essentially trying to add three-finger click or tap gestures to perform what [Middle](https://middleclick.app) does—adding middle-clicks for these.

I've tried searching for "Gesture matched" in the Console app for the "Multitouch" process, and I find it does not usually recognize the three-finger gestures. It happens infrequently (perhaps when the gesture is initially added?), but most of the time, it fails.

For what it's worth, the Middle app appears to have the same issue. It works initially, and then it quickly stops working.

I'm using the trial version 1.16.3 on macOS 10.15.1 (19B88), using a MacBook Pro (15-inch, 2019). Multitouch has been enabled under System Preferences, Security & Privacy, Privacy, Accessibility. I'm not running an app such as BetterTouchTool or Karabiner-Elements. Under Multitouch's preferences, all defaults are enabled, though I've tried at different sensitivities and with and without the private framework. No other gestures are enabled besides the three-finger click.

Let me know if I can supply any other information to help. Thanks in advance.

**Comment by emilyst** [comment]
Upon attempting to reproduce the issue, I have come to suspect this _may_ be related to using full-screen apps. (I tend to keep most apps open on their own space.) However, I have not yet identified a clear pattern.

I tried clearing the preferences and finding all data in Library for this app. (Obviously this made the Paddle functionality complain. I bought a license so I could proceed with testing this.) This did not help.

**Comment by rxhanson** [comment]
Hey, thanks for giving both apps a go and taking the time to write up your experience!

As you might expect, things work fine on my machine running Catalina so I will need some assistance in a debug effort. On my end, I need to go ahead and complete a small touch viewer app that will basically be identical in functionality to https://github.com/jnordberg/FingerMgmt but updated a bit to use my logic in Multitouch. That way we can run it and see exactly what Multitouch is seeing.

Perhaps try disabling palm rejection and thumb rejection and see if that helps:
`defaults write com.brassmonkery.Multitouch disablePalmRejection -bool true`
`defaults write com.brassmonkery.Multitouch disableThumbRejection -bool true`

You'll have to restart the app after executing those commands.

I'm assuming this is on the MBP trackpad, do you have an external trackpad you could try?

Also, I don't mind refunding you at any point in this process - just let me know when. Thanks!

**Comment by emilyst** [comment]
> Hey, thanks for giving both apps a go and taking the time to write up your experience!

I have been looking for something like this a while, so I'm glad to help.

> As you might expect, things work fine on my machine running Catalina so I will need some assistance in a debug effort. On my end, I need to go ahead and complete a small touch viewer app that will basically be identical in functionality to https://github.com/jnordberg/FingerMgmt but updated a bit to use my logic in Multitouch. That way we can run it and see exactly what Multitouch is seeing.

That does sound useful.

> Perhaps try disabling palm rejection and thumb rejection and see if that helps:
> `defaults write com.brassmonkery.Multitouch disablePalmRejection -bool true`
> `defaults write com.brassmonkery.Multitouch disableThumbRejection -bool true`
> 
> You'll have to restart the app after executing those commands.

Sadly, this did not help.

> I'm assuming this is on the MBP trackpad, do you have an external trackpad you could try?

Your assumption is correct. I grabbed a Magic Trackpad 2, and this actually gave an interesting result!

The functionality worked perfectly on the Magic Trackpad 2, and I was unable to make it misbehave. The Console dutifully logged all events as expected, and the middle-click worked, even in full-screen apps.

At the same time, the built-in trackpad continued to work inconsistently or not at all.

> Also, I don't mind refunding you at any point in this process - just let me know when. Thanks!

I appreciate your very prompt and kind offer. If I end up not using the app, then I will follow up. Thanks.

**Comment by rxhanson** [comment]
Thanks for the quick turnaround! 

My initial thought on this is that it is likely outside of the scope of something I can fix within the app. I've noticed that Apple's newer internal MBP trackpads are more likely to behave oddly than older MBP trackpads or external ones. But, it would be most interesting to have the visual feedback from said multitouch viewer app. Perhaps a pattern could be determined from this, and my touch detection algorithms can be adjusted to account for the discrepancies. I've often toyed with the idea of more in-depth logging that would expose such patterns, but perhaps the visual would give us all we need. 

My guess is that the third touch is intermittently not being passed from the hardware, and it causes enough of a gap in the touch count that my algorithms are assuming two finger touches. Along those lines, Apple's three finger swipe recognition either takes this into account, or when touches are swiped all three touches are passed from the hardware to the software. 

Will keep you posted when I've got the viewer ready for download.

**Comment by emilyst** [comment]
> Thanks for the quick turnaround!
> 
> My initial thought on this is that it is likely outside of the scope of something I can fix within the app. I've noticed that Apple's newer internal MBP trackpads are more likely to behave oddly than older MBP trackpads or external ones. But, it would be most interesting to have the visual feedback from said multitouch viewer app. Perhaps a pattern could be determined from this, and my touch detection algorithms can be adjusted to account for the discrepancies. I've often toyed with the idea of more in-depth logging that would expose such patterns, but perhaps the visual would give us all we need.
> 
> My guess is that the third touch is intermittently not being passed from the hardware, and it causes enough of a gap in the touch count that my algorithms are assuming two finger touches. Along those lines, Apple's three finger swipe recognition either takes this into account, or when touches are swiped all three touches are passed from the hardware to the software.
> 
> Will keep you posted when I've got the viewer ready for download.

Okie dokie, thanks. FWIW, the BetterTouchTool does somehow manage to do this, but who knows how?

**Comment by rxhanson** [comment]
Good to know, thanks!

**Comment by rxhanson** [comment]
Ok, I've released the first version of a viewing tool. You can grab it at the bottom of the page here: https://multitouch.app/versions (it's called Multiview)

You'll have to restart it after giving it accessibility privileges. It has a logging output view that shows a 3 digit code for each touch event that corresponds to the phases of the touches after they've been processed by the core functionality of Multitouch. Not necessary for you to know, but leftmost digit is quantity of ended touches, middle digit is touches that are already on the trackpad, and rightmost digit is quantity of touches that are beginning on the trackpad. Left mouse clicks are also logged. 

If you could pause the log viewer (cmd + L when it's in focus) and send logs corresponding to when you get failed clicks, that would be great. If you can visually from the viewer figure out any details on what's going on then, that would be awesome, too.

Something lacking from the logging is output for when a gesture is executed. If we need it for comparison purposes, I can push an update to Multiview.

Let me know if you have any issues. Thanks for taking the time to dig through this with me!

**Comment by emilyst** [comment]
> Ok, I've released the first version of a viewing tool. You can grab it at the bottom of the page here: https://multitouch.app/versions (it's called Multiview)
> 
> You'll have to restart it after giving it accessibility privileges. It has a logging output view that shows a 3 digit code for each touch event that corresponds to the phases of the touches after they've been processed by the core functionality of Multitouch. Not necessary for you to know, but leftmost digit is quantity of ended touches, middle digit is touches that are already on the trackpad, and rightmost digit is quantity of touches that are beginning on the trackpad. Left mouse clicks are also logged.
> 
> If you could pause the log viewer (cmd + L when it's in focus) and send logs corresponding to when you get failed clicks, that would be great. If you can visually from the viewer figure out any details on what's going on then, that would be awesome, too.
> 
> Something lacking from the logging is output for when a gesture is executed. If we need it for comparison purposes, I can push an update to Multiview.
> 
> Let me know if you have any issues. Thanks for taking the time to dig through this with me!

Sorry about the delay on responding to this. Frustratingly enough, I'm having a pretty hard time reproducing the issue now. Whenever I see it, I'll follow up.

**Comment by emilyst** [comment]
All right, here we go.

* [successful-middle-click-with-multitouch-open.log](https://github.com/rxhanson/Multitouch-Bugs/files/3807015/successful-middle-click-with-multitouch-open.log)
* [failed-middle-click-with-multitouch-open.log](https://github.com/rxhanson/Multitouch-Bugs/files/3807016/failed-middle-click-with-multitouch-open.log)

**Comment by rxhanson** [comment]
Excellent, thanks! I think I see a good way to fix this, so I should have a beta release ready momentarily.

**Comment by rxhanson** [comment]
Alright, I think **v1.16.4** (beta) should fix it: https://multitouch.app/versions

If it doesn't, I will update the Multiview logging so it gives us just a little more detail and try it again.

**Comment by emilyst** [comment]
Sadly, we might need a bit more detail. I didn't get a different result with that beta. Here's a new log from this morning: [failed-middle-click-with-multitouch-open.log](https://github.com/rxhanson/Multitouch-Bugs/files/3809989/failed-middle-click-with-multitouch-open.log).

It is pretty reliably failing at this point, for what it's worth.

**Comment by rxhanson** [comment]
Thanks for the quick feedback. I don't have a chance to push out a build with more detailed logging at the moment, but I should get to it tomorrow. That is a surprising result, so I'm intrigued as to what the detailed logging will show.

**Comment by rxhanson** [comment]
Ok, an updated version of Multiview (1.0.1) is available at https://multitouch.app/versions

This version is built with logging specifically for the three finger click, so there is no need to run Multitouch at the same time. 

Hopefully, this will give enough insight to tell me exactly what's going wrong. 

One more thing - do you have tap-to-click enabled in macOS preferences?

**Comment by emilyst** [comment]
> Ok, an updated version of Multiview (1.0.1) is available at https://multitouch.app/versions
> 
> This version is built with logging specifically for the three finger click, so there is no need to run Multitouch at the same time.

Very odd on this. I get different results depending on whether Multitouch is running.

* [failed-middle-click-with-multitouch-open.log](https://github.com/rxhanson/Multitouch-Bugs/files/3817369/failed-middle-click-with-multitouch-open.log)
* [failed-middle-click-with-multitouch-closed.log](https://github.com/rxhanson/Multitouch-Bugs/files/3817370/failed-middle-click-with-multitouch-closed.log)

In any case, Multitouch isn't working today.

> Hopefully, this will give enough insight to tell me exactly what's going wrong.
> 
> One more thing - do you have tap-to-click enabled in macOS preferences?

This was not enabled.

Oddly, I found that when it was not enabled, I was able to tap on it to enable it (which I wouldn't expect). Then I tapped again to disable it, and from that point, tap-to-click ceased to work.

This had no result on Multitouch.

**Comment by rxhanson** [comment]
> Very odd on this. I get different results depending on whether Multitouch is running.
This is actually expected - both apps will intercept click events so one of them is not going to receive them. The log with multitouch closed was all I needed. 

However, the unfortunate result of this is that it appears to work fine in Multiview. Which means that I'll have to build a verbose output log version of Multitouch - in hindsight, this is what I should have done from the start. The logic for both is identical, so I was expecting to see identical behavior, but Multitouch is where you can visibly reproduce it, so that's where the logging needs to be.

I really do appreciate your help on this! Sorry it's been such a process. I'll post back when I have a new debug Multitouch build.

**Comment by rxhanson** [comment]
Ok. Fingers crossed this is the last logging build we need: v1.16.5 at the bottom of https://multitouch.app/versions

This build uses the same logging window that was in Multiview. It should appear at launch of the app.

**Comment by emilyst** [comment]
This problem has been a bit of a bear, hasn't it? I'm kind of interested in seeing it through to the end, even if I have to record myself on video using the trackpad.

In any case, I'm attaching a much larger log this time. Here's what I can say about the activity it represents. I basically disabled and cleared the log to start with a fresh slate, then I enabled it with ⌘L, and then I triple-clicked on the log view until the problem occurred.

The first several clicks worked as expected. Then the final two clicks failed to middle-click.

After that, I stopped logging with ⌘L again and copied the log off for you here: [mixed-log-using-multiview-within-multitouch.log](https://github.com/rxhanson/Multitouch-Bugs/files/3822716/mixed-log-using-multiview-within-multitouch.log)

**Comment by rxhanson** [comment]
Quick question - when the three finger click fails, do you get the feedback (audible click) from the trackpad?

**Comment by emilyst** [comment]
The behavior when the three-finger click fails is the same as if I were not running Multitouch at all. It behaves as if I've two-finger clicked (a right-click), complete with the haptic feedback.

**Comment by rxhanson** [comment]
Ok, here's my take on what's going on.

MacOS has algorithms for determining which touch is a resting thumb. If one of the three touches is deemed as a thumb, the three finger click will actually be interpreted by macOS as the two finger right click. When a right click is executed, the event stream is temporarily blocked, and that's why we wouldn't see events properly in the logs. Essentially, a right click trumps what happens in Multitouch. 

On my 2016 MBP, the internal trackpad behaves very similar to what you describe if I use my thumb as one of the touches, while my external Magic Trackpad 2 doesn't. If I use three fingers and not my thumb, then both behave the same for me.

So why would you not see this with BTT? BTT is most likely blocking right clicks. I've always had a different philosophy with Multitouch, where I think of it as an app you use _with_ macOS, rather than an app that overrides and changes all the default macOS behavior. That was my original thought for allowing right clicks initially, but obviously that thought has led us down this long path.

So, the next step on this is to block the right clicks, or at least add it in as a configuration (most likely a hidden config). I'm AFK for the next week, but I'll see what I can do when I get back. If you don't want to wait and you feel you'd prefer to go ahead and get a refund, my feelings won't be hurt :)

Side note - a while back when I was writing my own thumb rejection algorithm, I tested out Apple's thumb rejection behavior pretty thoroughly and it's actually pretty complicated from an end-user perspective. While I could mimic a lot of it, there's some things they did that I didn't really understand.

**Comment by emilyst** [comment]
> Ok, here's my take on what's going on.
> 
> MacOS has algorithms for determining which touch is a resting thumb. If one of the three touches is deemed as a thumb, the three finger click will actually be interpreted by macOS as the two finger right click. When a right click is executed, the event stream is temporarily blocked, and that's why we wouldn't see events properly in the logs. Essentially, a right click trumps what happens in Multitouch.

Very interesting. That makes sense, and I haven't seen anything to contradict it.

> On my 2016 MBP, the internal trackpad behaves very similar to what you describe if I use my thumb as one of the touches, while my external Magic Trackpad 2 doesn't. If I use three fingers and not my thumb, then both behave the same for me.
> 
> So why would you not see this with BTT? BTT is most likely blocking right clicks. I've always had a different philosophy with Multitouch, where I think of it as an app you use _with_ macOS, rather than an app that overrides and changes all the default macOS behavior. That was my original thought for allowing right clicks initially, but obviously that thought has led us down this long path.

I think that's a pretty reasonable philosophy, and I'm sorry it hasn't panned out. I'm shocked, really, that macOS has the ability to middle-click, has functionality triggered by middle-clicking, and then gives you no way to actually do that unless you buy a hardware device that supplies it.

> So, the next step on this is to block the right clicks, or at least add it in as a configuration (most likely a hidden config). I'm AFK for the next week, but I'll see what I can do when I get back. If you don't want to wait and you feel you'd prefer to go ahead and get a refund, my feelings won't be hurt :)

At this point, you've put so much effort into this, I have no desire for a refund. You've certainly put more than $7 of work into this one bug, and that price is a pittance.

Happy to try whatever the new thing is when it's ready.

> Side note - a while back when I was writing my own thumb rejection algorithm, I tested out Apple's thumb rejection behavior pretty thoroughly and it's actually pretty complicated from an end-user perspective. While I could mimic a lot of it, there's some things they did that I didn't really understand.

It doesn't surprise me that Apple has put a considerable amount of complexity and expertise into making their trackpad, well, magic. It probably isn't a trivial problem. :)

**Comment by rxhanson** [comment]
Alright, thanks for your patience. I finally got a chance to try out blocking right clicks and unfortunately I was rather unpleased with the results. In my testing, there's still some notion of the event stream being jammed a bit by the right click even when I block it. I'm pretty certain that BTT does some manipulation of the gesture data that I don't do in Multitouch, and this might allow BTT to do this smoothly. 

In order to implement this in a good way, it seems to me to be a pretty deep rabbit hole that I don't intend to go down at this time. If I get a few more people that have the same desire for the three finger click, I'll gladly give this another look.

Sorry that all this effort didn't amount to anything at this moment, but I really do appreciate the time you took to test out all of these builds that I threw your way.

If anything else comes up, definitely let me know and I'll see what I can do.
