### ISSUE TITLE
Duplicate tab action for browsers

### ISSUE THREAD

**Issue by lorenzofanchi** [rxhanson/Multitouch-Bugs#58]
Dear Ryan, would be great if you could add the "Duplicate tab" option as an action, so I can bind it to a keyboard shortcut in e.g. Chrome :)

**Comment by rxhanson** [comment]
Good to hear from you again :)

https://multitouch.app/versions

v1.16.10 under pre-release

The only problem with this one is that there's not an easy way to automatically deselect the url bar after executing it (https://superuser.com/questions/726447/keyboard-shortcut-to-deselect-omnibox-in-chrome).

**Comment by lorenzofanchi** [comment]
Wow, you're lightning fast, as always :) Thanks for the update, I'll test and report back soon.

In the meantime, all the best to you and yours for 2020!

**Comment by lorenzofanchi** [comment]
Some initial observations:
* I have to hit the key combo twice in Chrome (v80) to duplicate the current tab
* setting the shortcut key prevents it from working in other apps (e.g. the shortcut key does not work in Lightroom anymore)

Would it be possible to have the shortcut key only triggering in Chrome/Firefox/Safari and not "hijack" the shortcut in other apps?

**Comment by rxhanson** [comment]
> I have to hit the key combo twice in Chrome (v80) to duplicate the current tab

Does the url bar get highlighted after the initial keypress? I'll need to improve the timing in Multitouch.

> setting the shortcut key prevents it from working in other apps (e.g. the shortcut key does not trigger the expected action in Lightroom anymore)

I can fix this, but it might take a little while to get the change in - it's a slightly involved fix.

**Comment by lorenzofanchi** [comment]
> > I have to hit the key combo twice in Chrome (v80) to duplicate the current tab
> Does the url bar get highlighted after the initial keypress? I'll need to improve the timing in Multitouch.

Indeed it does.

> > setting the shortcut key prevents it from working in other apps (e.g. the shortcut key does not trigger the expected action in Lightroom anymore)
> 
> I can fix this, but it might take a little while to get the change in - it's a slightly involved fix.

This would be really essential though for comfortable use, so would be great if you could get it to work :)

**Comment by rxhanson** [comment]
Alright, try out v1.16.11 under pre-release on https://multitouch.app/versions.

Let me know how it works.

**Comment by lorenzofanchi** [comment]
Just. Perfect. :)

Action works as expected in Chrome now, and not hijacking the shortcut in other apps. Love it!

Thank you

**Comment by rxhanson** [comment]
Awesome, thanks for trying it out so soon!

**Comment by lorenzofanchi** [comment]
One more question: when duplicating tabs in Chrome (v80) through Multitouch, the duplicated tab opens at the end of all my tabs. When I select "Duplicate tab" from the right-click menu, it opens next to the current tab. Is this a known limitation or could you mimic the "normal" behavior?

**Comment by rxhanson** [comment]
This is a known limitation, and it's based on what I have readily available to work with. As you might have guessed, Multitouch's interface with Chrome (and it's thankfully identical across browsers) is the combination of cmd + L and cmd + enter. 

To get what you want, you actually don't need Multitouch at all. Just mimic what I outline in this blog post about assigning keyboard shortcuts to menu items: https://medium.com/ryan-hanson/going-without-a-3rd-party-window-manager-in-macos-catalina-4bd270b29245

The post is for window actions, but it's pretty obvious what you need to do for duplicate tab.

**Comment by lorenzofanchi** [comment]
Ah right, indeed when you mentioned timing I had a hunch. Still very valuable for Multitouch nonetheless.

Thanks for the Medium link, the method you posted works well!
