### ISSUE TITLE
App downloads as ZIP file from Multitouch website

### ISSUE THREAD

**Issue by lorenzofanchi** [rxhanson/Multitouch-Bugs#59]
Dear Ryan, just a quick FYI: when I download the binary from the Multitouch website through Chrome (v80), the downloaded file gets a ZIP extension. Attempts to extract the file fail, as expected. Doing the same in Safari results in a DMG file, which works flawlessly.

**Comment by rxhanson** [comment]
Thanks for letting me know. It works properly for me on Chrome (79), Firefox, and Safari, but maybe this will be the push that finally makes me change up the way that I host the site and the download.

**Comment by rxhanson** [comment]
This one should now be resolved as I finally got around to changing up the hosting. Thanks again for letting me know about the issue!
