### ISSUE TITLE
Feature request: Add optional modifier key to gesture

### ISSUE THREAD

**Issue by isakkeyten** [rxhanson/Multitouch-Bugs#61]

**Comment by rxhanson** [comment]
This is something I've been planning on for a long time, and I've finally implemented a "modifier key recorder" in a fork of MASShortcut (which is used for all the other keyboard shortcut recording in Multitouch). My plan is to add this into the next major release of Multitouch, along with per gesture double-tap configuration. I'll post back here once the next major release is scheduled.

**Comment by isakkeyten** [comment]
Ok cool. For extra flexibility, maybe make it so there is a global modifier key for all gestures, and per gesture option that would essentially override the global one.

**Comment by rxhanson** [comment]
This is now in v1.17 (pre-release). Let me know if you try it out. In this release, I added an action for disabling/enabling all gestures via a keyboard shortcut. I don't have plans to add in per-gesture disabling.
