### ISSUE TITLE
One click tap to disable the move/resize trackpad

### ISSUE THREAD

**Issue by cotfas** [rxhanson/Multitouch-Bugs#63]
I use the following:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/3340367/76102092-25cd2f00-5fd8-11ea-8a4c-eaa89a16d8af.png">

<img width="666" alt="image" src="https://user-images.githubusercontent.com/3340367/76102158-3da4b300-5fd8-11ea-8168-5f0dde181247.png">

<img width="668" alt="image" src="https://user-images.githubusercontent.com/3340367/76102185-45fcee00-5fd8-11ea-9e5e-13f9bdb95d9b.png">

<img width="662" alt="image" src="https://user-images.githubusercontent.com/3340367/76102205-501eec80-5fd8-11ea-9c64-0eb21ec8c1fe.png">

<img width="668" alt="image" src="https://user-images.githubusercontent.com/3340367/76102420-a724c180-5fd8-11ea-837f-4b28a740c187.png">

When I do the 3 finger tap or 4 finger tap and move the cursor with the trackpad it works for resize/move, but in order to release it from resize/move I have to do another 3 finger tap or 4 finger tap. What can I do in order to release it with one finger trackpad tap (I saw it works with 1 finger trackpad click, but is unproductive).

Thank you.

**Comment by rxhanson** [comment]
https://github.com/rxhanson/Multitouch-Bugs/issues/53

As mentioned in that issue, the only way to have this work would be if I implemented three finger drag myself in Multitouch. I don't have plans to implement that in the near future.

**Comment by rxhanson** [comment]
Ok, I read through this one again and I think I understand it now. It's not an issue with the three finger drag. 

However, adding the ability to one finger tap cancel the move/resize is a one-off addition that would be a rather difficult setting to convey in the UI. I'll think about this one a bit more and I won't close it out, but I'm not sure if I'll roll this one in or not. If there's an elegant way to implement it then I'll see what I can do.

**Comment by cotfas** [comment]
For the resize I found a better usability and it works best:

<img width="520" alt="image" src="https://user-images.githubusercontent.com/3340367/76145074-cc740700-608e-11ea-9e36-6bbc641d41c7.png">

I do the right tap and then resizing and when I no longer need it when I release the left thumb the resize action is released which is great.

**Comment by rxhanson** [comment]
Glad you got some thing that works! Closing this one out :)

**Comment by cotfas** [comment]
I kinda need it. I now use the two finger for move, and 4 finger tap to resize.

**Comment by cotfas** [comment]
Not needed anymore.

🥇 for the double tap feature on these:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/3340367/78836551-fa849800-79fa-11ea-80ea-5dcda898c033.png">

I find it very convenient for 1 tap to move and 2 taps to resize and wow, it works directly without removing the main finger when moving/resizing.
