### ISSUE TITLE
iTerm Reside issue

### ISSUE THREAD

**Issue by cotfas** [rxhanson/Multitouch-Bugs#65]
Multitouch: 1.17.4 (84)
macOS: Version 10.15.4 (Build 19E266)
Model: MacBookPro14,2
Devices: ["internalTrackpad2:144115188092633088:16777216","magicMouse:288230378114662828:1962951084"]
Multitouch Configuration: [{"gid":{"gesture":"oneClickTopRight"},"r":{"type":2,"action":205}},{"gid":{"gesture":"onePlusLeftMouse"},"r":{"type":15,"action":1502}},{"gid":{"gesture":"twoPlusLeftMouse"},"r":{"type":15,"action":1502}},{"gid":{"gesture":"onePlusRight"},"r":{"type":15,"action":1502}},{"gid":{"gesture":"twoLeftEdgeSwipe"},"r":{"type":12}},{"gid":{"gesture":"fourForce"},"r":{"type":15,"action":1501}},{"gid":{"gesture":"oneForce"},"r":{"type":3,"action":300}},{"gid":{"gesture":"oneClickBottomRight"},"r":{"type":2,"action":206}},{"gid":{"gesture":"oneClickTopLeft"},"r":{"type":2,"action":208}},{"gid":{"gesture":"onePlusLeft"},"r":{"type":15,"action":1502}},{"gid":{"gesture":"oneClickBottomLeft"},"r":{"type":2,"action":209}},{"gid":{"gesture":"oneForceBottomRight"},"r":{"type":1,"keyCode":45,"modifierFlags":1048576}},{"gid":{"gesture":"fourClick"},"r":{"type":15,"action":1504}},{"gid":{"gesture":"oneForceTopRight"},"r":{"type":2,"action":214}},{"gid":{"gesture":"fourTap"},"r":{"type":15,"action":1503}}]
Avoid Private Framework: false

iTerm Build 3.3.10beta3

4 finger tap to resize does not work well on iTerm. So far only on iTerm I saw this issue.

**Comment by rxhanson** [comment]
This is a bug with iTerm that has to do with the way it resizes windows based on character sizing (the default behavior). 

A workaround is to make iTerm resize based on pixels instead of character sizing with the following terminal command, followed by a restart of iTerm:

`defaults write com.googlecode.iterm2 DisableWindowSizeSnap -integer 1`

**Comment by cotfas** [comment]
And how I will switch it back?

**Comment by cotfas** [comment]
Found it in settings with search: "snap". Thanks
