### ISSUE TITLE
Suggestion app as PrefPane?

### ISSUE THREAD

**Issue by cotfas** [rxhanson/Multitouch-Bugs#67]
Suggestion to make the app as a PrefPane so it does not stays in the statusbar?
*I know already using Bartender but still will be a nice idea:)

**Comment by rxhanson** [comment]
When I first created the app, I actually thought about this a lot. Ultimately, I found that having the app in a preference pane was a worse user experience. Thanks for the suggestion, but I have no plans to implement this.
