### ISSUE TITLE
The program does not work on the MacBook Pro M1

### ISSUE THREAD

**Issue by lovipomidorku** [rxhanson/Multitouch-Bugs#83]
Hello dear developer! I used your program on my old Macbook on an Intel chipset and everything worked fine. But after buying a MacBook Pro M1, the program does not work. It does not allow you to record your keyboard shortcut. 

When writing, she does not see letters, numbers and arrows. The screenshot shows all the keys that the program allows you to record

MacBook Pro M1. OSX BigSur 11.4

<img width="319" alt="Снимок экрана 2021-06-29 в 00 17 25" src="https://user-images.githubusercontent.com/33869604/123661296-673db980-d86f-11eb-98ed-ae003b37540c.png">

**Comment by rxhanson** [comment]
I think there might be some confusion between "Restrictions" and "Actions". The shortcut recorder that only allows modifier keys is a way of restricting your gesture to only execute when you hold the corresponding modifier keys. Your one plus swipe up there would only register if you held control, option, shift, and command.

To configure a gesture to execute a keyboard shortcut, in the dropdown for "Action", select Shortcut & Key Entry -> Keyboard Shortcut. This is where you'll find the shortcut recorder that is for which keyboard shortcut will be executed when you perform the gesture.

Let me know if that is not clear or is not the issue.

**Comment by lovipomidorku** [comment]
Thank you. This is my cant

**Comment by rxhanson** [comment]
Thanks for following up. Honestly, the UI is a little confusing so I don't blame you :)
