### ISSUE TITLE
If 'Restart on Wake' settings is enabled, the App window will show up each time I wake my MacBook

### ISSUE THREAD

**Issue by dingwen07** [rxhanson/Multitouch-Bugs#95]
This happens after upgrading to version 1.27.

**Comment by rxhanson** [comment]
Thanks! Please update to 1.27.1 and let me know how it goes.

https://www.multitouch.app/downloads/multitouch1.27.1.dmg

**Comment by dingwen07** [comment]
> Thanks! Please update to 1.27.1 and let me know how it goes.
> 
> https://www.multitouch.app/downloads/multitouch1.27.1.dmg

Doesn't seem to happen in 1.27.1.
