### ISSUE TITLE
Is there a way to adjust the size of the "center half?"

### ISSUE THREAD

**Issue by TreYager** [rxhanson/Multitouch-Bugs#97]
I use an ultrawide monitor and often use the action "Move window to center half." However, the window is a bit too narrow. I'd prefer something more like "move window to center 2/3" if that makes sense. Is there a variable I can adjust somewhere to increase the window width a bit when using this action?

**Comment by rxhanson** [comment]
Not center half, but you can adjust "Almost maximize" with terminal commands to get what you want:

By default, "Almost Maximize" will resize the window to 90% of the screen (width & height).

`defaults write com.brassmonkery.Multitouch almostMaximizeHeight -float <VALUE_BETWEEN_0_&_1>`

`defaults write com.brassmonkery.Multitouch almostMaximizeWidth -float <VALUE_BETWEEN_0_&_1>`

For the height, you'll want 1. 

Then restart the app.

**Comment by TreYager** [comment]
Works perfectly! Thanks!
